### ISSUE TITLE
F1修改建议

### ISSUE THREAD

**Issue by SinnerAiZ** [zengli666/web_tasks#4]
整体完成的很不错，但还是有较多需要改进的地方
## 登录界面
1. 代码缩进不规范，此外，H5文档申明需大写
```HTML
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
<link rel="stylesheet" href="css/F1_login.css">
</head>
<body>
```
2. 把id选择器改成类名等选择器， 并且禁用`!important`，请通过其它方式提高样式优先级
``` CSS
@media(max-width:768px){
    #description{
        margin-bottom:10% !important;
    }
    #formInnerWrapper{
        margin-top:5% !important;
    }
    .formInput{
        ma

rgin-bottom:30% !important;
    }
    #materialForm{
        margin-top:10% !important;
    }
}
```
3. 整体样式太丑，不符合效果图，此外，基本没用到检查所要求的boots框架

### 功能方面bug
1. 只能添加一位学生或无法显示所有学生
2. 刷新后学生信息就没了
3. 一打开页面的时候所有表单都出现在同一个页面，并没有分页，这是样式bug？

### 代码优化
1. 这里直接通过css设置不可见就好了，不应该通过js实现，多此一举
```JS
function myfun() {
  $(".add").hide();
  $(".find").hide();
  $(".delete").hide();
  $(".rewrite").hide();
}
window.onload = myfun;
```
2. 像这些经常使用的节点不应该在每次执行函数的时候都重新查找，太消耗资源了，应该在初始化的时候获取这些节点并缓存到一个全局对象中
```JS
function Find_show() {
  $(".add").hide();
  $(".find").show();
  $(".delete").hide();
  $(".rewrite").hide();
}

function Delete_show() {
  $(".add").hide();
  $(".find").hide();
  $(".delete").show();
  $(".rewrite").hide();
}

function Rewrite_show() {
  $(".add").hide();
  $(".find").hide();
  $(".delete").hide();
  $(".rewrite").show();
  $(".old_form").show();
  $(".new_form").hide();
}
```
3. 仅仅通过判断`localStorage`的长度有点草率，长度并不一定是学生数目，还可能保存了其它信息; 此外，建议把学生信息保存为嵌套的对象，每一个子对象通过学号作为键值，这样有利于提高遍历速度

原代码：
```JS
for (i; i < localStorage.length; i++) {
      var id = localStorage.key(i);
      var str = localStorage.getItem(id);
      var stu = JSON.parse(str);
```
更改示例：
```JS
var targetId; // 需要查找的id
var stus = JSON.parse(localStorage.getItem("stuSys"));
for(var i in stus) {
  if (i == targetId) return stus[i]
}
```
